// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7SCRCMleBUV9VuRfNFVCe89Md2Uqxnz0',
    appId: '1:556776901551:web:31f2e208f84831d51d7d5a',
    messagingSenderId: '556776901551',
    projectId: 'aurabake',
    authDomain: 'aurabake.firebaseapp.com',
    storageBucket: 'aurabake.firebasestorage.app',
    measurementId: 'G-Q5S7379ZZW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAucEhM-Kuc6uO0599UcafCG2BbnX1AMHE',
    appId: '1:556776901551:android:07c791e12790eb031d7d5a',
    messagingSenderId: '556776901551',
    projectId: 'aurabake',
    storageBucket: 'aurabake.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6NI7LNDZg_EVZAah95j011Gn_dTJaItk',
    appId: '1:556776901551:ios:0c3f87f4555fa8f71d7d5a',
    messagingSenderId: '556776901551',
    projectId: 'aurabake',
    storageBucket: 'aurabake.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7SCRCMleBUV9VuRfNFVCe89Md2Uqxnz0',
    appId: '1:556776901551:web:4bc82e8c45c137ef1d7d5a',
    messagingSenderId: '556776901551',
    projectId: 'aurabake',
    authDomain: 'aurabake.firebaseapp.com',
    storageBucket: 'aurabake.firebasestorage.app',
    measurementId: 'G-B3WL261DGP',
  );
}
